# Module - Benchmarking
Ontime provides a `Benchmark` class that can be used to run a number of prediction models on a number of datasets.

In [1]:
from ontime.module.benchmarking import BenchmarkMode, BenchmarkDataset, BenchmarkMetric, BenchmarkModelConfig, Benchmark
import ontime as on

## Initialization
A `Benchmark` instance can be initialized with a list of datasets, models and metrics to run through. When invoking `run()`, it will train (if needed) and test every dataset on every model, and compute every metric on the predicted data.

### Preparing datasets

Datasets submitted to a `Benchmark` must be of type `TimeSeries`, wrapped into `BenchmarkDataset`. `BenchmarkDataset` allows to give datasets a name, give training and test splits, define the time series components to use as target, and define how data will be split to perform a rolling evaluation. 
The dataset given to the wrapper can instantiated or not, allowing to avoid potential memory issues. In the latter case, a processing function can be given so that time series can be pre-processed when loaded.

In [2]:
from ontime.module.datasets.dataset import Dataset
from darts.utils.missing_values import fill_missing_values # for filling missing values in the time series (for models that don't handle missing values)

datasets = [
    BenchmarkDataset(on.TimeSeries.from_darts(fill_missing_values(Dataset.TemperatureDataset.load())), input_length=96, target_length=24, gap=0, stride=96, name="Daily temperature"),
    BenchmarkDataset(Dataset.ETTh1Dataset, input_length=336, gap=0, stride=72, target_length=72, name = "ETTh1", target_columns=["OT"], processing_fn=lambda ts: ts[:5000])
]

### Preparing models  

Benchmark models must be given in a `BenchmarkModelConfig` class object, and their class must implement ontime `AbstractModel` interface. The `BenchmarkModelConfig` class contains attribute that allows to later instantiate the model with the desired configuration.
It requires the following parameters :
- `model_name` : the name of the model, for result logging purpose,
- `model_class` : the class of the model that implements `AbstractModel` interface,
- `benchmark_mode` : the mode in which the model must be evaluted:
    - if `ZERO_SHOT`, the model is not trained, and the evaluation is done on the test set. It is used for models that already has trained weights, available through checkpoints, or for some models from darts, where predictions are directly made using the fitted data as input (such as ARIMA),
    - if `FULL_SHOT`, the model is trained on the entire given training set. Once trained, the model is evaluated using the learnt weights.
- `static_model_params` : the static parameters to give to the model class for instantiating it. This parameters can be defined when instatiating the `BenchmarkModelConfig` object.
- `dynamic_model_params` : the dynamic parameters to give to the model class for instantiating it. This parameters can only be known when the dataset on which the model is trained is known. Therefore, a callable object that take a `BenchmarkDataset` must be given.

In [3]:
from ontime.core.time_series.time_series import TimeSeries
from ontime import Model
from darts.models import ExponentialSmoothing, TCNModel

# torch related parameters
pl_trainer_kwargs = {
    "accelerator": "cpu",
    "enable_progress_bar": False
    }

# dynamic parameters callback
input_length_param = lambda ds: ds.input_length
target_length_param = lambda ds: ds.target_length


model_configs = [
    BenchmarkModelConfig("ExponentialSmoothing", model_class=Model, benchmark_mode=BenchmarkMode.ZERO_SHOT, static_model_params={"model" : ExponentialSmoothing()}),
    BenchmarkModelConfig("Temporal Convolutional Network", model_class=Model, benchmark_mode=BenchmarkMode.FULL_SHOT, 
                         static_model_params={"model":TCNModel, "n_epochs":2, "pl_trainer_kwargs":pl_trainer_kwargs}, 
                         dynamic_model_params={"input_chunk_length":input_length_param, "output_chunk_length":target_length_param})
]

### Preparing metrics
Metrics must be given to the `BenchmarkMetric` constructor. If the function can't be invoked as is in `BenchmarkMetric`'s implementation, a child class can be written and submitted.

In [4]:
import darts.metrics

metrics = [
   BenchmarkMetric(name="MAE", metric_function=darts.metrics.metrics.mae),
   BenchmarkMetric(name="sMAPE", metric_function=darts.metrics.metrics.smape),
   BenchmarkMetric(name="MASE", metric_function=darts.metrics.metrics.mase)
]

## Creating and running a Benchmark

In [5]:
benchmark = Benchmark(datasets=datasets,
                      model_configs=model_configs, 
                      metrics=metrics)

Datasets, models and metrics can also be added after instanciation.

In [6]:
benchmark.add_dataset(BenchmarkDataset(Dataset.ETTh2Dataset.load()[:5000], input_length=336, gap=0, stride=72, target_length=72, name = "ETTh2", target_columns=["OT"]))

Once the models and datasets have been added, the `run()` method will train instances of all the models on all the datasets individually and compute metrics. The logging level can be chosen to show less or more information about the benchmark execution in the console.

In [7]:
benchmark.run(logging_level="debug")

on 0: 17:51:30 - [INFO] - BenchmarkLogger - On Daily temperature dataset...

on 0: 17:51:30 - [INFO] - BenchmarkLogger - On 100.0% of training data...

on 1: 17:51:30 - [INFO] - BenchmarkLogger - ExponentialSmoothing model...

on 1: 17:51:30 - [INFO] - BenchmarkLogger - Evaluating...

on 1: 17:51:31 - [INFO] - BenchmarkLogger - Evaluation done, took 0.6998634338378906

on 1: 17:51:31 - [INFO] - BenchmarkLogger - getting predictions...

on 1: 17:51:31 - [INFO] - BenchmarkLogger - Computed metrics:
       {'MAE': 2.400040758215776, 'sMAPE': 24.148347520589876, 'MASE': 1.259049717016714}

on 2: 17:51:31 - [INFO] - BenchmarkLogger - Temporal Convolutional Network model...

on 2: root       INFO  Training ...

on 2: darts.models.forecasting.torch_forecasting_model INFO  Train dataset contains 2216 samples.

on 2: darts.models.forecasting.tcn_model INFO  Number of layers chosen: 5

on 2: darts.models.forecasting.torch_forecasting_model INFO  Time series values are 64-bits; casting model to float64.

on 2: INFO: GPU available: True (cuda), used: False

on 2: lightning.pytorch.utilities.rank_zero INFO  GPU available: True (cuda), used: False

on 2: INFO: TPU available: False, using: 0 TPU cores

on 2: lightning.pytorch.utilities.rank_zero INFO  TPU available: False, using: 0 TPU cores

on 2: INFO: HPU available: False, using: 0 HPUs

on 2: lightning.pytorch.utilities.rank_zero INFO  HPU available: False, using: 0 HPUs

on 2: /home/benjy/.cache/pypoetry/virtualenvs/ontime-2OQVvbNf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/setup.py:177: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.

        | Name            | Type             | Params | Mode
      -------------------------------------------------------------
      0 | criterion       | MSELoss          | 0      | train
      1 | train_criterion | MSELoss          | 0      | train
      2 | val_criterion   | MSELoss          | 0      | train
      3 | train_metrics   | MetricCollection | 0      | train
      4 | val_metrics     | MetricCollection | 0      | train
      5 | res_blocks      | ModuleList       | 272    | train
      -------------------------------------------------------------
      272       Trainable params
      0         Non-trainable params
      272       Total params
      0.001     Total estimated model params size (MB)
      33        Modules in train mode
      0         Modules in eval mode

on 2: INFO: `Trainer.fit` stopped: `max_epochs=2` reached.

on 2: lightning.pytorch.utilities.rank_zero INFO  `Trainer.fit` stopped: `max_epochs=2` reached.

on 2: 17:51:36 - [INFO] - BenchmarkLogger - Training done, it took 4.88862419128418

on 2: 17:51:36 - [INFO] - BenchmarkLogger - Evaluating...

on 2: INFO: GPU available: True (cuda), used: False

on 2: lightning.pytorch.utilities.rank_zero INFO  GPU available: True (cuda), used: False

on 2: INFO: TPU available: False, using: 0 TPU cores

on 2: lightning.pytorch.utilities.rank_zero INFO  TPU available: False, using: 0 TPU cores

on 2: INFO: HPU available: False, using: 0 HPUs

on 2: lightning.pytorch.utilities.rank_zero INFO  HPU available: False, using: 0 HPUs

on 2: 17:51:36 - [INFO] - BenchmarkLogger - Evaluation done, took 0.6731932163238525

on 2: 17:51:36 - [INFO] - BenchmarkLogger - getting predictions...

on 2: INFO: GPU available: True (cuda), used: False

on 2: lightning.pytorch.utilities.rank_zero INFO  GPU available: True (cuda), used: False

on 2: INFO: TPU available: False, using: 0 TPU cores

on 2: lightning.pytorch.utilities.rank_zero INFO  TPU available: False, using: 0 TPU cores

on 2: INFO: HPU available: False, using: 0 HPUs

on 2: lightning.pytorch.utilities.rank_zero INFO  HPU available: False, using: 0 HPUs

on 2: /home/benjy/.cache/pypoetry/virtualenvs/ontime-2OQVvbNf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/setup.py:177: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.
      17:51:37 - [INFO] - BenchmarkLogger - Computed metrics:
       {'MAE': 2.356975522754001, 'sMAPE': 23.61342665109934, 'MASE': 1.2266879796748433}

on 2: 17:51:37 - [INFO] - BenchmarkLogger - On ETTh1 dataset...

on 2: 17:51:37 - [INFO] - BenchmarkLogger - On 100.0% of training data...

on 3: 17:51:37 - [INFO] - BenchmarkLogger - ExponentialSmoothing model...

on 3: 17:51:37 - [INFO] - BenchmarkLogger - Evaluating...

on 3: 17:51:49 - [INFO] - BenchmarkLogger - Evaluation done, took 11.69727349281311

on 3: 17:51:49 - [INFO] - BenchmarkLogger - getting predictions...

on 3: 17:51:50 - [INFO] - BenchmarkLogger - Computed metrics:
       {'MAE': 2.5759203585774157, 'sMAPE': 35.774323416320925, 'MASE': 3.7807843519910174}

on 4: 17:51:50 - [INFO] - BenchmarkLogger - Temporal Convolutional Network model...

on 4: root       INFO  Training ...

on 4: darts.models.forecasting.torch_forecasting_model INFO  Train dataset contains 2791 samples.

on 4: darts.models.forecasting.tcn_model INFO  Number of layers chosen: 7

on 4: darts.models.forecasting.torch_forecasting_model INFO  Time series values are 64-bits; casting model to float64.

on 4: INFO: GPU available: True (cuda), used: False

on 4: lightning.pytorch.utilities.rank_zero INFO  GPU available: True (cuda), used: False

on 4: INFO: TPU available: False, using: 0 TPU cores

on 4: lightning.pytorch.utilities.rank_zero INFO  TPU available: False, using: 0 TPU cores

on 4: INFO: HPU available: False, using: 0 HPUs

on 4: lightning.pytorch.utilities.rank_zero INFO  HPU available: False, using: 0 HPUs

on 4: /home/benjy/.cache/pypoetry/virtualenvs/ontime-2OQVvbNf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/setup.py:177: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.

        | Name            | Type             | Params | Mode
      -------------------------------------------------------------
      0 | criterion       | MSELoss          | 0      | train
      1 | train_criterion | MSELoss          | 0      | train
      2 | val_criterion   | MSELoss          | 0      | train
      3 | train_metrics   | MetricCollection | 0      | train
      4 | val_metrics     | MetricCollection | 0      | train
      5 | res_blocks      | ModuleList       | 548    | train
      -------------------------------------------------------------
      548       Trainable params
      0         Non-trainable params
      548       Total params
      0.002     Total estimated model params size (MB)
      43        Modules in train mode
      0         Modules in eval mode

on 4: INFO: `Trainer.fit` stopped: `max_epochs=2` reached.

on 4: lightning.pytorch.utilities.rank_zero INFO  `Trainer.fit` stopped: `max_epochs=2` reached.

on 4: 17:52:00 - [INFO] - BenchmarkLogger - Training done, it took 10.261582612991333

on 4: 17:52:00 - [INFO] - BenchmarkLogger - Evaluating...

on 4: INFO: GPU available: True (cuda), used: False

on 4: lightning.pytorch.utilities.rank_zero INFO  GPU available: True (cuda), used: False

on 4: INFO: TPU available: False, using: 0 TPU cores

on 4: lightning.pytorch.utilities.rank_zero INFO  TPU available: False, using: 0 TPU cores

on 4: INFO: HPU available: False, using: 0 HPUs

on 4: lightning.pytorch.utilities.rank_zero INFO  HPU available: False, using: 0 HPUs

on 4: 17:52:02 - [INFO] - BenchmarkLogger - Evaluation done, took 2.3786513805389404

on 4: 17:52:02 - [INFO] - BenchmarkLogger - getting predictions...

on 4: INFO: GPU available: True (cuda), used: False

on 4: lightning.pytorch.utilities.rank_zero INFO  GPU available: True (cuda), used: False

on 4: INFO: TPU available: False, using: 0 TPU cores

on 4: lightning.pytorch.utilities.rank_zero INFO  TPU available: False, using: 0 TPU cores

on 4: INFO: HPU available: False, using: 0 HPUs

on 4: lightning.pytorch.utilities.rank_zero INFO  HPU available: False, using: 0 HPUs

on 4: /home/benjy/.cache/pypoetry/virtualenvs/ontime-2OQVvbNf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/setup.py:177: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.
      17:52:03 - [INFO] - BenchmarkLogger - Computed metrics:
       {'MAE': 3.3460838961336226, 'sMAPE': 37.499484962786866, 'MASE': 4.961040899725449}

on 4: 17:52:03 - [INFO] - BenchmarkLogger - On ETTh2 dataset...

on 4: 17:52:03 - [INFO] - BenchmarkLogger - On 100.0% of training data...

on 5: 17:52:03 - [INFO] - BenchmarkLogger - ExponentialSmoothing model...

on 5: 17:52:03 - [INFO] - BenchmarkLogger - Evaluating...

on 5: 17:52:13 - [INFO] - BenchmarkLogger - Evaluation done, took 10.262415885925293

on 5: 17:52:13 - [INFO] - BenchmarkLogger - getting predictions...

on 5: 17:52:14 - [INFO] - BenchmarkLogger - Computed metrics:
       {'MAE': 28.95317395909225, 'sMAPE': 119.18358091417018, 'MASE': 49.36630385605498}

on 6: 17:52:14 - [INFO] - BenchmarkLogger - Temporal Convolutional Network model...

on 6: root       INFO  Training ...

on 6: darts.models.forecasting.torch_forecasting_model INFO  Train dataset contains 2791 samples.

on 6: darts.models.forecasting.tcn_model INFO  Number of layers chosen: 7

on 6: darts.models.forecasting.torch_forecasting_model INFO  Time series values are 64-bits; casting model to float64.

on 6: INFO: GPU available: True (cuda), used: False

on 6: lightning.pytorch.utilities.rank_zero INFO  GPU available: True (cuda), used: False

on 6: INFO: TPU available: False, using: 0 TPU cores

on 6: lightning.pytorch.utilities.rank_zero INFO  TPU available: False, using: 0 TPU cores

on 6: INFO: HPU available: False, using: 0 HPUs

on 6: lightning.pytorch.utilities.rank_zero INFO  HPU available: False, using: 0 HPUs

on 6: /home/benjy/.cache/pypoetry/virtualenvs/ontime-2OQVvbNf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/setup.py:177: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.

        | Name            | Type             | Params | Mode
      -------------------------------------------------------------
      0 | criterion       | MSELoss          | 0      | train
      1 | train_criterion | MSELoss          | 0      | train
      2 | val_criterion   | MSELoss          | 0      | train
      3 | train_metrics   | MetricCollection | 0      | train
      4 | val_metrics     | MetricCollection | 0      | train
      5 | res_blocks      | ModuleList       | 548    | train
      -------------------------------------------------------------
      548       Trainable params
      0         Non-trainable params
      548       Total params
      0.002     Total estimated model params size (MB)
      43        Modules in train mode
      0         Modules in eval mode

on 6: INFO: `Trainer.fit` stopped: `max_epochs=2` reached.

on 6: lightning.pytorch.utilities.rank_zero INFO  `Trainer.fit` stopped: `max_epochs=2` reached.

on 6: 17:52:24 - [INFO] - BenchmarkLogger - Training done, it took 10.19582462310791

on 6: 17:52:24 - [INFO] - BenchmarkLogger - Evaluating...

on 6: INFO: GPU available: True (cuda), used: False

on 6: lightning.pytorch.utilities.rank_zero INFO  GPU available: True (cuda), used: False

on 6: INFO: TPU available: False, using: 0 TPU cores

on 6: lightning.pytorch.utilities.rank_zero INFO  TPU available: False, using: 0 TPU cores

on 6: INFO: HPU available: False, using: 0 HPUs

on 6: lightning.pytorch.utilities.rank_zero INFO  HPU available: False, using: 0 HPUs

on 6: 17:52:25 - [INFO] - BenchmarkLogger - Evaluation done, took 0.6809611320495605

on 6: 17:52:25 - [INFO] - BenchmarkLogger - getting predictions...

on 6: INFO: GPU available: True (cuda), used: False

on 6: lightning.pytorch.utilities.rank_zero INFO  GPU available: True (cuda), used: False

on 6: INFO: TPU available: False, using: 0 TPU cores

on 6: lightning.pytorch.utilities.rank_zero INFO  TPU available: False, using: 0 TPU cores

on 6: INFO: HPU available: False, using: 0 HPUs

on 6: lightning.pytorch.utilities.rank_zero INFO  HPU available: False, using: 0 HPUs

on 6: /home/benjy/.cache/pypoetry/virtualenvs/ontime-2OQVvbNf-py3.10/lib/python3.10/site-packages/pytorch_lightning/trainer/setup.py:177: GPU available but not used. You can set it by doing `Trainer(accelerator='gpu')`.
      17:52:26 - [INFO] - BenchmarkLogger - Computed metrics:
       {'MAE': 23.261690067842224, 'sMAPE': 93.84464880173626, 'MASE': 39.52277881741283}

Benchmarking |████████████████████| 6/6 [100%] in 56.4s (0.11/s)

## Visualizing results

The benchmark automatically stores measures and metrics computed during the run, available through class attributes.

### Measures and metrics
To view the results, you can call `get_report()` and print the returned value

In [8]:
print(benchmark.get_report())

Daily temperature dataset:
nb features: 1
target column: ['Daily minimum temperatures']
training set size: 2920
test set size: 732
validation set proportion: 0.2
few shot proportions: [1.0]

100.0% of training data:

ExponentialSmoothing model:
suceeded: ✓
times: {'training': 0, 'evaluation': 0.6998634338378906, 'inference': 0.08935046195983887}
metrics: {'MAE': 2.400040758215776, 'sMAPE': 24.148347520589876, 'MASE': 1.259049717016714}

Temporal Convolutional Network model:
suceeded: ✓
times: {'training': 4.88862419128418, 'evaluation': 0.6731932163238525, 'inference': 0.38167881965637207}
metrics: {'MAE': 2.356975522754001, 'sMAPE': 23.61342665109934, 'MASE': 1.2266879796748433}


ETTh1 dataset:
nb features: 7
target column: ['OT']
training set size: 3999
test set size: 1001
validation set proportion: 0.2
few shot proportions: [1.0]

100.0% of training data:

ExponentialSmoothing model:
suceeded: ✓
times: {'training': 0, 'evaluation': 11.69727349281311, 'inference': 1.061882734298706}
metrics: {'MAE': 2.5759203585774157, 'sMAPE': 35.774323416320925, 'MASE': 3.7807843519910174}

Temporal Convolutional Network model:
suceeded: ✓
times: {'training': 10.261582612991333, 'evaluation': 2.3786513805389404, 'inference': 0.42870211601257324}
metrics: {'MAE': 3.3460838961336226, 'sMAPE': 37.499484962786866, 'MASE': 4.961040899725449}


ETTh2 dataset:
nb features: 7
target column: ['OT']
training set size: 3999
test set size: 1001
validation set proportion: 0.2
few shot proportions: [1.0]

100.0% of training data:

ExponentialSmoothing model:
suceeded: ✓
times: {'training': 0, 'evaluation': 10.262415885925293, 'inference': 1.0754601955413818}
metrics: {'MAE': 28.95317395909225, 'sMAPE': 119.18358091417018, 'MASE': 49.36630385605498}

Temporal Convolutional Network model:
suceeded: ✓
times: {'training': 10.19582462310791, 'evaluation': 0.6809611320495605, 'inference': 0.46220898628234863}
metrics: {'MAE': 23.261690067842224, 'sMAPE': 93.84464880173626, 'MASE': 39.52277881741283}

You can also get results as dataframes by calling `get_report_df()`. The results are then returned as a dataframe with model names as columns, dataset names as main rows, and measure as sub rows.

In [9]:
df_1, df_2 = benchmark.get_report_dfs()
df_1

                                      Daily temperature  ETTh1  ETTh2
Characteristic
nb features                                           1      7      7
target column              [Daily minimum temperatures]   [OT]   [OT]
training set size                                  2920   3999   3999
test set size                                       732   1001   1001
validation set proportion                           0.2    0.2    0.2
few shot proportions                              [1.0]  [1.0]  [1.0]

In [10]:
df_2

                                                  ExponentialSmoothing  \
Few-shot proportion Dataset           Metric
100.0%              Daily temperature training                0.000000
                                      evaluation              0.699863
                                      inference               0.089350
                                      MAE                     2.400041
                                      sMAPE                  24.148348
                                      MASE                    1.259050
                    ETTh1             training                0.000000
                                      evaluation             11.697273
                                      inference               1.061883
                                      MAE                     2.575920
                                      sMAPE                  35.774323
                                      MASE                    3.780784
                    ETTh2             training                0.000000
                                      evaluation             10.262416
                                      inference               1.075460
                                      MAE                    28.953174
                                      sMAPE                 119.183581
                                      MASE                   49.366304

                                                  Temporal Convolutional Network
Few-shot proportion Dataset           Metric
100.0%              Daily temperature training                          4.888624
                                      evaluation                        0.673193
                                      inference                         0.381679
                                      MAE                               2.356976
                                      sMAPE                            23.613427
                                      MASE                              1.226688
                    ETTh1             training                         10.261583
                                      evaluation                        2.378651
                                      inference                         0.428702
                                      MAE                               3.346084
                                      sMAPE                            37.499485
                                      MASE                              4.961041
                    ETTh2             training                         10.195825
                                      evaluation                        0.680961
                                      inference                         0.462209
                                      MAE                              23.261690
                                      sMAPE                            93.844649
                                      MASE                             39.522779

### Plotting

By default (argument `nb_predictions` of `benchmark.run()` method), the benchmark will generate a prediction for one random input sample of each dataset with each model. The predictions, along input and target series, are stored in a dictionnary and can be retrieved by calling `benchmark.get_predictions()`. The predictions can be plotted using the Ontime plotting module.

In [11]:
# currently, Ontime plotting module needs the time index to be named 'time'
def rename_index(ts, name='time'):
    df = ts.pd_dataframe()
    df.rename_axis(name, inplace=True)
    return TimeSeries.from_dataframe(df)

In [12]:
predictions = benchmark.get_predictions()

In [13]:
input = rename_index(predictions['inputs']['Daily temperature'][0]).rename({'Daily minimum temperatures': 'input'})
target = rename_index(predictions['targets']['Daily temperature'][0]).rename({'Daily minimum temperatures': 'target'})
prediction = rename_index(predictions['predictions']['Daily temperature'][1.0]['Temporal Convolutional Network'][0]).rename({'Daily minimum temperatures': 'prediction'})

In [14]:
(on.Plot()
    .add(on.marks.line, input)
    .add(on.marks.line, target)
    .add(on.marks.line, prediction, type='dashed')
    .properties(width=600, height=200)
    .show()
)

alt.LayerChart(...)

In [15]:
prediction = rename_index(predictions['predictions']['Daily temperature'][1.0]['ExponentialSmoothing'][0]).rename({'Daily minimum temperatures': 'prediction'})

In [16]:
(on.Plot()
    .add(on.marks.line, input)
    .add(on.marks.line, target)
    .add(on.marks.line, prediction, type='dashed')
    .properties(width=600, height=200)
    .show()
)

alt.LayerChart(...)

In [17]:
input = rename_index(predictions['inputs']['ETTh1'][0].univariate_component(0)[220:]).rename({'HUFL': 'input'})
target = rename_index(predictions['targets']['ETTh1'][0].univariate_component(0)).rename({'HUFL': 'target'})
prediction = rename_index(predictions['predictions']['ETTh1'][1.0]['ExponentialSmoothing'][0].univariate_component(0)).rename({'HUFL': 'prediction'})

In [18]:
(on.Plot()
    .add(on.marks.line, input)
    .add(on.marks.line, target)
    .add(on.marks.line, prediction, type='dashed')
    .properties(width=600, height=200)
    .show()
)

alt.LayerChart(...)