# Module - Benchmarking
Ontime provides a `Benchmark` class that can be used to run a number of prediction models on a number of datasets.

In [1]:
from ontime.module.benchmarking import BenchmarkDataset, BenchmarkMetric, BenchmarkModelConfig, Benchmark
import ontime as on

/Users/benjamin.pasquier/projects/ontime/.venv/lib/python3.11/site-packages/fs/__init__.py:4: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  __import__("pkg_resources").declare_namespace(__name__)  # type: ignore

## Initialization
A `Benchmark` instance can be initialized with a list of datasets, models and metrics to run through. When invoking `run()`, it will train (if needed) and test every dataset on every model, and compute every metric on the predicted data.

### Preparing datasets

Datasets submitted to a `Benchmark` must be of type `TimeSeries`, wrapped into `BenchmarkDataset`. `BenchmarkDataset` allows to give datasets a name, give training and test splits, define the time series components to use as target, define normalization scaling to use, and define how data will be split to perform a rolling evaluation. While `BenchmarkDataset` contains information about training data, it is designed primarly to have a common test dataset, and therefore to allow an unified evaluation.  

More specifically, `BenchmarkDataset` defines :
- test proportion to split the whole given dataset time series, e.g. 0.3 for using 30% of the whole series as test set :  
<img src="img/ts_data_splitting_docs.drawio.svg" alt="Times series splitting" width="500">  
- input, target, gap and stride length to define how test data will be split for creating test samples, as well as target columns to define which columns/components are used as target, i.e. the columns/components that has to be predicted   
<img src="img/ts_test_samples_split_docs.drawio.svg" alt="Times series splitting" width="500"> <img src="img/ts_convention_docs.drawio.svg" alt="Times series splitting" width="500">  

The dataset given to the wrapper can be instantiated or not, allowing to avoid potential memory issues. In the latter case, a processing function can be given so that time series can be pre-processed once loaded.

In [2]:
from ontime.module.datasets.dataset import Dataset
from darts.utils.missing_values import fill_missing_values # for filling missing values in the time series (for models that don't handle missing values)
from sklearn.preprocessing import StandardScaler

datasets = [
    # loaded time series, with standard normalization
    BenchmarkDataset(on.TimeSeries.from_darts(fill_missing_values(Dataset.TemperatureDataset.load())), 
                     input_length=96, 
                     target_length=24, 
                     gap=0, 
                     stride=96, 
                     name="Daily temperature",
                     scaler_type=StandardScaler
    ),
    # unloaded time series, without normalization
    BenchmarkDataset(Dataset.ETTh1Dataset, 
                     input_length=336, 
                     gap=0, 
                     stride=72, 
                     target_length=72, 
                     name = "ETTh1", 
                     target_columns=["OT"], 
                     processing_fn=lambda ts: ts[:5000])
]

### Preparing models

Benchmark models must be given in a `BenchmarkModelConfig` class object, and their class must implement ontime `AbstractModel` interface. The `BenchmarkModelConfig` class contains attribute that allows to later instantiate the model with the desired configuration.
It requires the following parameters :
- `model_name` : the name of the model, for result logging purpose,
- `model_class` : the class of the model that implements `AbstractModel` interface,
- `zero_shot_only` : either if the model must be evaluated in zero shot learning setting only.
    - if `True`, the model is not trained, and the evaluation is done on the test set. It is used for models that already has trained weights, available through checkpoints, or for some models from darts, where predictions are directly made using the fitted data as input (such as ARIMA),
    - if `False`, the model is trained on the entire given training set. Once trained, the model is evaluated using the learnt weights.
- `static_model_params` : the static parameters to give to the model class for instantiating it. This parameters can be defined when instantiating the `BenchmarkModelConfig` object.
- `dynamic_model_params` : the dynamic parameters to give to the model class for instantiating it. This parameters can only be known when the dataset on which the model is trained is known. Therefore, a callable object that take a `BenchmarkDataset` must be given.
- `dynamic_fit_model_params` : the additional dynamic parameters to give to the model fit method during the benchmark run. This parameters can only be known when the dataset on which the model is trained is known. Therefore, a callable object that take a `BenchmarkDataset` must be given.
- `dynamic_predict_model_params` : the additional dynamic parameters to give to the model predict method during the benchmark run.. This parameters can only be known when the dataset on which the model is trained is known. Therefore, a callable object that take a `BenchmarkDataset` must be given.

In [9]:
from ontime import Model
from darts.models import ExponentialSmoothing, TCNModel

# torch related parameters
pl_trainer_kwargs = {
    "accelerator": "cpu",
    "enable_progress_bar": False
    }

# dynamic parameters callback
input_length_param = lambda ds: ds.input_length
target_length_param = lambda ds: ds.target_length

model_configs = [
    BenchmarkModelConfig("ExponentialSmoothing", model_class=Model, zero_shot_only=True, static_model_params={"wrapped_model" : ExponentialSmoothing()}),
    BenchmarkModelConfig("Temporal Convolutional Network", model_class=Model, zero_shot_only=False,
                         static_model_params={"wrapped_model":TCNModel, "n_epochs":2, "pl_trainer_kwargs":pl_trainer_kwargs},
                         dynamic_model_params={"input_chunk_length":input_length_param, "output_chunk_length":target_length_param})
]

### Preparing metrics
Metrics must be given to the `BenchmarkMetric` constructor. If the function can't be invoked as is in `BenchmarkMetric`'s implementation, a child class can be written and submitted.

In [10]:
import darts.metrics

metrics = [
   BenchmarkMetric(name="MAE", metric_function=darts.metrics.metrics.mae),
   BenchmarkMetric(name="sMAPE", metric_function=darts.metrics.metrics.smape),
   BenchmarkMetric(name="MASE", metric_function=darts.metrics.metrics.mase)
]

## Creating and running a Benchmark

The benchmark is created trough the `Benchmark` class, to which datasets, model configurations and metrics must be provided.  
In addition, proportions of the train set, as floats, can be provided to train and evaluate models in varied few shot learning settings. E.g. by setting `few_shot_proportions` to `[1.0, 0.8, 0.2, 0.0], one full-shot learning (100% of training data), two few-shot learning (80 and 20% of training data) and one zero-shot learning (no training data) training and evaluation will be performed.
<img src="img/ts_data_splitting_few_shot_docs.drawio.svg" alt="Times series splitting" width="1000">  
Lastly, a string directory path can be passed in order to create a folder in which intermediate results will be saved. By default, the directory path is "/benchmark_results".

In [11]:
benchmark = Benchmark(datasets=datasets,
                      model_configs=model_configs, 
                      metrics=metrics,
                      few_shot_proportions=[0.4, 0.8, 1.0])

Datasets, models and metrics can also be added after instanciation, using respectively `add_dataset()`, `add_model_config()` and `add_metric()` methods.

In [12]:
benchmark.add_dataset(BenchmarkDataset(Dataset.ETTh2Dataset.load()[:5000], input_length=336, gap=0, stride=72, target_length=72, name = "ETTh2", target_columns=["OT"]))

Once the models and datasets have been added, the `run()` method will train instances of all the models on all the datasets individually and compute metrics. The logging level can be chosen to show less or more information about the benchmark execution in the console. A run name can be given in order to create the run directory where intermediate results will be saved. By default, it will creates a directory named "benchmark_*time*". The `save_all_predictions` argument allows to save all the predictions made by the model, in case we would need them to compute other metrics afterwards, avoiding to launch a full benchmark again.

In [ ]:
benchmark.run(logging_level="debug", run_name="benchmark_doc_example", save_all_predictions=True)

## Visualizing results

The benchmark automatically stores measures and metrics computed during the run, available through class attributes.

### Measures and metrics
To view the results, you can call `get_report()` and print the returned value

In [14]:
print(benchmark.get_report())

Dataset: Daily temperature

nb features                1
target column              ['Daily minimum temperatures']
training set size          2920
test set size              732
validation set proportion  0.2

Results:

+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+-------+--------+---------+
| Model                          | Few-shot %   |    | Success   |    |   evaluation |   inference |   training |    |   MAE |   MASE |   sMAPE |
+================================+==============+====+===========+====+==============+=============+============+====+=======+========+=========+
| ExponentialSmoothing           | 0%           |    | ✓         |    |         0.19 |        0.03 |       0    |    | 2.4   |  1.259 |  24.148 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+-------+--------+---------+
| Temporal Convolutional Network | 40%          |    | ✓         |    |         0.07 |        0.02 |       1.19 |    | 2.437 |  1.271 |  24.39  |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+-------+--------+---------+
| Temporal Convolutional Network | 80%          |    | ✓         |    |         0.07 |        0.02 |       2.46 |    | 2.12  |  1.101 |  21.538 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+-------+--------+---------+
| Temporal Convolutional Network | 100%         |    | ✓         |    |         0.08 |        0.02 |       3.12 |    | 2.074 |  1.074 |  21.142 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+-------+--------+---------+

Dataset: ETTh1

nb features                7
target column              ['OT']
training set size          3999
test set size              1001
validation set proportion  0.2

Results:

+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+-------+--------+---------+
| Model                          | Few-shot %   |    | Success   |    |   evaluation |   inference |   training |    |   MAE |   MASE |   sMAPE |
+================================+==============+====+===========+====+==============+=============+============+====+=======+========+=========+
| ExponentialSmoothing           | 0%           |    | ✓         |    |         2.92 |        0.28 |       0    |    | 2.576 |  3.781 |  35.772 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+-------+--------+---------+
| Temporal Convolutional Network | 40%          |    | ✓         |    |         0.5  |        0.03 |       2.18 |    | 2.429 |  3.539 |  31.273 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+-------+--------+---------+
| Temporal Convolutional Network | 80%          |    | ✓         |    |         0.49 |        0.02 |       5.4  |    | 4.364 |  6.466 |  45.392 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+-------+--------+---------+
| Temporal Convolutional Network | 100%         |    | ✓         |    |         0.51 |        0.03 |       7.11 |    | 5.412 |  8.007 |  52.699 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+-------+--------+---------+

Dataset: ETTh2

nb features                7
target column              ['OT']
training set size          3999
test set size              1001
validation set proportion  0.2

Results:

+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+--------+--------+---------+
| Model                          | Few-shot %   |    | Success   |    |   evaluation |   inference |   training |    |    MAE |   MASE |   sMAPE |
+================================+==============+====+===========+====+==============+=============+============+====+========+========+=========+
| ExponentialSmoothing           | 0%           |    | ✓         |    |         2.55 |        0.27 |       0    |    | 28.953 | 49.366 | 119.184 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+--------+--------+---------+
| Temporal Convolutional Network | 40%          |    | ✓         |    |         0.08 |        0.02 |       2.3  |    |  7.119 | 12.203 |  44.332 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+--------+--------+---------+
| Temporal Convolutional Network | 80%          |    | ✓         |    |         0.08 |        0.02 |       5.55 |    | 24.731 | 42.005 |  96.842 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+--------+--------+---------+
| Temporal Convolutional Network | 100%         |    | ✓         |    |         0.08 |        0.02 |       7.16 |    | 19.076 | 32.359 |  84.154 |
+--------------------------------+--------------+----+-----------+----+--------------+-------------+------------+----+--------+--------+---------+

You can also get results as dataframes by calling `get_report_df()`. The results are then returned as a dataframe with model names as columns, dataset names as main rows, and measure as sub rows.

In [15]:
df_1, df_2 = benchmark.get_report_dfs()
df_1

                                      Daily temperature ETTh1 ETTh2
Characteristic
nb features                                           1     7     7
target column              [Daily minimum temperatures]  [OT]  [OT]
training set size                                  2920  3999  3999
test set size                                       732  1001  1001
validation set proportion                           0.2   0.2   0.2

In [16]:
df_2

                                                                Daily temperature  \
Model                          Few-shot proportion Metric/Time
ExponentialSmoothing           0.0%                training              0.000000
                                                   evaluation            0.189349
                                                   inference             0.025302
                                                   MAE                   2.400068
                                                   sMAPE                24.148496
                                                   MASE                  1.259063
Temporal Convolutional Network 40.0%               training              1.189721
                                                   evaluation            0.073067
                                                   inference             0.023217
                                                   MAE                   2.437351
                                                   sMAPE                24.390081
                                                   MASE                  1.270973
                               80.0%               training              2.458294
                                                   evaluation            0.072752
                                                   inference             0.023978
                                                   MAE                   2.120467
                                                   sMAPE                21.537911
                                                   MASE                  1.101018
                               100.0%              training              3.121504
                                                   evaluation            0.075160
                                                   inference             0.023491
                                                   MAE                   2.073939
                                                   sMAPE                21.142095
                                                   MASE                  1.073699

                                                                    ETTh1  \
Model                          Few-shot proportion Metric/Time
ExponentialSmoothing           0.0%                training      0.000000
                                                   evaluation    2.921396
                                                   inference     0.276232
                                                   MAE           2.575732
                                                   sMAPE        35.772201
                                                   MASE          3.780530
Temporal Convolutional Network 40.0%               training      2.178518
                                                   evaluation    0.504545
                                                   inference     0.025868
                                                   MAE           2.428723
                                                   sMAPE        31.272688
                                                   MASE          3.538546
                               80.0%               training      5.404808
                                                   evaluation    0.485207
                                                   inference     0.024913
                                                   MAE           4.363631
                                                   sMAPE        45.391707
                                                   MASE          6.466033
                               100.0%              training      7.108728
                                                   evaluation    0.511577
                                                   inference     0.025446
                                                   MAE           5.411634
                                                   sMAPE        52.699459
                                                   MASE          8.006780

                                                                     ETTh2
Model                          Few-shot proportion Metric/Time
ExponentialSmoothing           0.0%                training       0.000000
                                                   evaluation     2.546445
                                                   inference      0.274501
                                                   MAE           28.953211
                                                   sMAPE        119.183679
                                                   MASE          49.366363
Temporal Convolutional Network 40.0%               training       2.297462
                                                   evaluation     0.084331
                                                   inference      0.023887
                                                   MAE            7.118667
                                                   sMAPE         44.332339
                                                   MASE          12.203235
                               80.0%               training       5.547349
                                                   evaluation     0.081724
                                                   inference      0.023356
                                                   MAE           24.730934
                                                   sMAPE         96.842307
                                                   MASE          42.005021
                               100.0%              training       7.162837
                                                   evaluation     0.083527
                                                   inference      0.023311
                                                   MAE           19.075788
                                                   sMAPE         84.154229
                                                   MASE          32.358763

### Plotting

By default (argument `nb_predictions` of `benchmark.run()` method), the benchmark will generate a prediction for one random input sample of each dataset with each model. The predictions, along input and target series, are stored in a dictionnary and can be retrieved by calling `benchmark.get_predictions()`. The predictions can be plotted using the Ontime plotting module.

In [17]:
predictions = benchmark.get_predictions()

In [18]:
input = predictions['inputs']['Daily temperature'][0].rename({'Daily minimum temperatures': 'input'})
target = predictions['targets']['Daily temperature'][0].rename({'Daily minimum temperatures': 'target'})
prediction = predictions['predictions']['Daily temperature']['Temporal Convolutional Network'][1.0][0].rename({'Daily minimum temperatures': 'prediction'})

In [19]:
(on.Plot()
    .add(on.marks.line, input)
    .add(on.marks.line, target)
    .add(on.marks.line, prediction, type='dashed')
    .properties(width=600, height=200)
    .show()
)

alt.LayerChart(...)

In [20]:
prediction = predictions['predictions']['Daily temperature']['ExponentialSmoothing'][0.0][0].rename({'Daily minimum temperatures': 'prediction'})

In [21]:
(on.Plot()
    .add(on.marks.line, input)
    .add(on.marks.line, target)
    .add(on.marks.line, prediction, type='dashed')
    .properties(width=600, height=200)
    .show()
)

alt.LayerChart(...)

In [22]:
input = predictions['inputs']['ETTh1'][0].univariate_component(0)[220:].rename({'HUFL': 'input'})
target = predictions['targets']['ETTh1'][0].univariate_component(0).rename({'HUFL': 'target'})
prediction = predictions['predictions']['ETTh1']['ExponentialSmoothing'][0.0][0].univariate_component(0).rename({'HUFL': 'prediction'})

In [23]:
(on.Plot()
    .add(on.marks.line, input)
    .add(on.marks.line, target)
    .add(on.marks.line, prediction, type='dashed')
    .properties(width=600, height=200)
    .show()
)

alt.LayerChart(...)

### Loading back saved results

You can load the results and models predictions back in python if needed, using pickle and/or json libraries.

In [24]:
import pickle, json

# load saved data
with open("benchmark_results/benchmark_doc_example/predictions.pkl", "rb") as f:
    loaded_preds = pickle.load(f)

with open("benchmark_results/benchmark_doc_example/results.json", "r") as f:
    loaded_results = json.load(f)

with open("benchmark_results/benchmark_doc_example/all_predictions/Temporal Convolutional Network_ETTh1_0.4.pkl", "rb") as f:
    some_preds = pickle.load(f)

In [25]:
Benchmark.get_results_df(loaded_results)

                                                                Daily temperature  \
Model                          Few-shot proportion Metric/Time
ExponentialSmoothing           0.0%                training              0.000000
                                                   evaluation            0.189349
                                                   inference             0.025302
                                                   MAE                   2.400068
                                                   sMAPE                24.148496
                                                   MASE                  1.259063
Temporal Convolutional Network 40.0%               training              1.189721
                                                   evaluation            0.073067
                                                   inference             0.023217
                                                   MAE                   2.437351
                                                   sMAPE                24.390081
                                                   MASE                  1.270973
                               80.0%               training              2.458294
                                                   evaluation            0.072752
                                                   inference             0.023978
                                                   MAE                   2.120467
                                                   sMAPE                21.537911
                                                   MASE                  1.101018
                               100.0%              training              3.121504
                                                   evaluation            0.075160
                                                   inference             0.023491
                                                   MAE                   2.073939
                                                   sMAPE                21.142095
                                                   MASE                  1.073699

                                                                    ETTh1  \
Model                          Few-shot proportion Metric/Time
ExponentialSmoothing           0.0%                training      0.000000
                                                   evaluation    2.921396
                                                   inference     0.276232
                                                   MAE           2.575732
                                                   sMAPE        35.772201
                                                   MASE          3.780530
Temporal Convolutional Network 40.0%               training      2.178518
                                                   evaluation    0.504545
                                                   inference     0.025868
                                                   MAE           2.428723
                                                   sMAPE        31.272688
                                                   MASE          3.538546
                               80.0%               training      5.404808
                                                   evaluation    0.485207
                                                   inference     0.024913
                                                   MAE           4.363631
                                                   sMAPE        45.391707
                                                   MASE          6.466033
                               100.0%              training      7.108728
                                                   evaluation    0.511577
                                                   inference     0.025446
                                                   MAE           5.411634
                                                   sMAPE        52.699459
                                                   MASE          8.006780

                                                                     ETTh2
Model                          Few-shot proportion Metric/Time
ExponentialSmoothing           0.0%                training       0.000000
                                                   evaluation     2.546445
                                                   inference      0.274501
                                                   MAE           28.953211
                                                   sMAPE        119.183679
                                                   MASE          49.366363
Temporal Convolutional Network 40.0%               training       2.297462
                                                   evaluation     0.084331
                                                   inference      0.023887
                                                   MAE            7.118667
                                                   sMAPE         44.332339
                                                   MASE          12.203235
                               80.0%               training       5.547349
                                                   evaluation     0.081724
                                                   inference      0.023356
                                                   MAE           24.730934
                                                   sMAPE         96.842307
                                                   MASE          42.005021
                               100.0%              training       7.162837
                                                   evaluation     0.083527
                                                   inference      0.023311
                                                   MAE           19.075788
                                                   sMAPE         84.154229
                                                   MASE          32.358763

In [26]:
some_preds[0].plot()

alt.LayerChart(...)